name: when2heat
channels:
  - defaults
  - conda-forge
dependencies:
  - attrs=18.2.0=py37h28b3542_0
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - bleach=3.0.2=py37_0
  - bzip2=1.0.6=hfa6e2cd_5
  - ca-certificates=2018.03.07=0
  - certifi=2018.11.29=py37_0
  - cftime=1.0.3.4=py37h8c2d366_0
  - click=7.0=py37_0
  - click-plugins=1.0.4=py37_0
  - cligj=0.5.0=py37_0
  - colorama=0.4.1=py37_0
  - curl=7.63.0=h2a8f88b_1000
  - cycler=0.10.0=py37_0
  - decorator=4.3.0=py37_0
  - descartes=1.1.0=py37_0
  - entrypoints=0.2.3=py37_2
  - et_xmlfile=1.0.1=py37_0
  - expat=2.2.5=he025d50_0
  - fiona=1.8.4=py37h22081e2_0
  - freetype=2.9.1=ha9979f8_1
  - freexl=1.0.5=hfa6e2cd_0
  - gdal=2.3.3=py37hdf43c64_0
  - geopandas=0.4.0=py37_1
  - geos=3.7.1=h33f27b4_0
  - hdf4=4.2.13=h712560f_2
  - hdf5=1.10.4=h7ebc959_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha66f8fd_1
  - intel-openmp=2019.1=144
  - ipykernel=5.1.0=py37h39e3cac_0
  - ipython=7.2.0=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.4.2=py37_0
  - jdcal=1.4=py37_0
  - jedi=0.13.2=py37_0
  - jinja2=2.10=py37_0
  - jpeg=9b=hb83a4c4_2
  - jsonschema=2.6.0=py37_0
  - jupyter=1.0.0=py37_7
  - jupyter_client=5.2.4=py37_0
  - jupyter_console=6.0.0=py37_0
  - jupyter_core=4.4.0=py37_0
  - kealib=1.4.7=h07cbb95_6
  - kiwisolver=1.0.1=py37h6538335_0
  - krb5=1.16.1=hc04afaa_7
  - libboost=1.67.0=hd9e427e_4
  - libcurl=7.63.0=h2a8f88b_1000
  - libgdal=2.3.3=h10f50ba_0
  - libiconv=1.15=h1df5818_7
  - libkml=1.3.0=he5f2a48_4
  - libnetcdf=4.6.1=h411e497_2
  - libpng=1.6.35=h2a8f88b_0
  - libpq=11.1=h3235a2c_0
  - libsodium=1.0.16=h9d3ae62_0
  - libspatialindex=1.8.5=h6538335_2
  - libspatialite=4.3.0a=hc36aec2_19
  - libssh2=1.8.0=h7a1dbc1_4
  - libtiff=4.0.9=h36446d0_2
  - libxml2=2.9.8=hadb2253_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=1.1.0=py37he774522_0
  - matplotlib=3.0.2=py37hc8f65d3_0
  - mistune=0.8.4=py37he774522_0
  - mkl=2019.1=144
  - mkl_fft=1.0.6=py37h6288b17_0
  - mkl_random=1.0.2=py37h343c172_0
  - msys2-conda-epoch=20160418=1
  - munch=2.3.2=py37_0
  - nbconvert=5.3.1=py37_0
  - nbformat=4.4.0=py37_0
  - netcdf4=1.4.2=py37h812ae01_0
  - notebook=5.7.4=py37_0
  - numpy=1.15.4=py37h19fb1c0_0
  - numpy-base=1.15.4=py37hc3f5095_0
  - openpyxl=2.5.12=py37_0
  - openssl=1.1.1a=he774522_0
  - pandas=0.23.4=py37h830ac7b_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.3.1=py37_0
  - pcre=8.42=hd6b2f15_0
  - pickleshare=0.7.5=py37_0
  - pip=18.1=py37_0
  - proj4=5.2.0=ha925a31_1
  - prometheus_client=0.5.0=py37_0
  - prompt_toolkit=2.0.7=py37_0
  - psycopg2=2.7.6.1=py37h7a1dbc1_0
  - pygments=2.3.1=py37_0
  - pyparsing=2.3.0=py37_0
  - pyproj=1.9.5.1=py37h6782396_1
  - pyqt=5.9.2=py37h6538335_2
  - pysal=1.14.4=py37_0
  - python=3.7.2=h8c8aaf0_0
  - python-dateutil=2.7.5=py37_0
  - pytz=2018.7=py37_0
  - pywinpty=0.5.5=py37_1000
  - pyyaml=3.13=py37hfa6e2cd_0
  - pyzmq=17.1.2=py37hfa6e2cd_0
  - qt=5.9.7=vc14h73c81de_0
  - qtconsole=4.4.3=py37_0
  - rtree=0.8.3=py37_0
  - scipy=1.1.0=py37h29ff71c_2
  - send2trash=1.5.0=py37_0
  - setuptools=40.6.3=py37_0
  - shapely=1.6.4=py37h222a598_0
  - sip=4.19.8=py37h6538335_0
  - six=1.12.0=py37_0
  - sqlalchemy=1.2.15=py37he774522_0
  - sqlite=3.26.0=he774522_0
  - terminado=0.8.1=py37_1
  - testpath=0.4.2=py37_0
  - tk=8.6.8=hfa6e2cd_0
  - tornado=5.1.1=py37hfa6e2cd_0
  - traitlets=4.3.2=py37_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.15.26706=h3a45250_0
  - wcwidth=0.1.7=py37_0
  - webencodings=0.5.1=py37_1
  - wheel=0.32.3=py37_0
  - widgetsnbextension=3.4.2=py37_0
  - wincertstore=0.2=py37_0
  - winpty=0.4.3=4
  - xerces-c=3.2.2=ha925a31_0
  - xz=5.2.4=h2fa13f4_4
  - yaml=0.1.7=hc54c509_2
  - zeromq=4.2.5=he025d50_1
  - zlib=1.2.11=h62dcd97_3
  - pip:
    - ecmwf-api-client==1.4.2

