name: when2heat
channels:
  - defaults
  - conda-forge
dependencies:
  - geopandas=0.4.0
  - jupyter
  - netcdf4=1.4.2
  - pandas=0.23.4
  - python=3.7.2
  - pyyaml
  - pip:
    - ecmwf-api-client==1.4.2
